project:
  type: website

website:
  title: "Akasha Strub"
  favicon: "images/headshot_circular.png"
  navbar:
    
    left:
      - href: index.qmd
        text: Blog
      - href: about.qmd
        text: About
      - href: resume.qmd
        text: Resume
        
    right:
      - icon: linkedin
        href: https://linkedin.com/in/akashastrub
        aria-label: Quarto LinkedIn
      - icon: github
        href: https://github.com/akashastrub/
        aria-label: Quarto Github
      - icon: envelope
        href: mailto:akashastrub@gmail.com
        aria-label: Quarto Email
        
  search: 
    location: navbar
    type: overlay
    
format:
  html:
    theme: litera
    css: styles.css

editor: visual

execute:
  freeze: auto

